### PR TITLE
[start #162557862] created register form with with simple vaidation

### PR DESCRIPTION
**Pull request by a-braham**
#### What does this PR do?
 * The pool request creates registration form that a user should fill to be able to login the system

#### Description of Task to be completed?
  **Have the following features complete**
  * Registration should have simple validation
  * Page should be responsive
  * Should have all the required fields

#### How should this be manually tested?
  Responsiveness can be tested by maximising the browser or testing smaller screens
 
#### Screenshots
  
screenshot from 2018-12-12 11-13-52

#### What are the relevant pivotal tracker stories?
  #162557862

### CODE REVIEW

**Comment by Bakley** [comment]
Nice work buddy, is your app responsive?

**Comment by munniomer** [comment]
Nice Work @a-braham

**Comment by a-braham** [comment]
@Bakley @munniomer  Thank you
The app is responsive

**Comment by Ogutu-Brian** [comment]
@a-braham , this is a great work

**Comment by Philipotieno** [comment]
Good one

**Pull request merged**
